// examples/courseman/fe-angular/src/app/pattern/pattern.component.ts
import {
    Component
} from '@angular/core';

@Component({
    selector: 'PatternComponent',
    template: '<ng-content></ng-content>'
})
export class PatternComponent {
    providers: any[] = [];

    registerProvider(provider: any) {
        provider.pattern = this;
        this.providers.push(provider);
    }

    render() {
        
    }
}

// examples/courseman/fe-reactjs/src/common/patterns/Pattern.js
import React from "react"

export default class Pattern extends React.Component {
    constructor(props) {
        super(props)
        this.state = {}
        this.providers = Array()
    }

    componentDidMount() {
        console.log("hello")
    }

    registerProvider(provider) {
        provider.pattern = this
        this.providers.push(provider)
    }
}
