// examples/courseman/fe-angular/src/app/modules/base/pattern/model-region.ts
import { Directive, ElementRef, Host, Input, Renderer2, ViewContainerRef } from '@angular/core';
import { PatternService } from './pattern.service';

@Directive({
    selector: '[modelRegion]',
})
export class ModelRegionDirective {
    @Input() modelRegion = '';

    constructor(
        @Host() public element: ElementRef,
        private patternService: PatternService
    ) { }

    ngAfterViewInit() {
        this.patternService.renderModelRegion(this);
    }
}

// examples/courseman/fevuejs/src/components/common/pattern/modelregion.vue
<template>
    <div v-bind:region="modelRegion"></div>
</template>

<script>
import PatternService from './pattern.service';

export default {
    name: 'ModelRegion',
    props: {
        modelRegion: {
            type: String,
            default: ''
        }
    },
    inject: ['element'],
    created() {
        PatternService.renderModelRegion(this);
    }
}
</script>
