// examples/courseman/fe-angular/src/app/modules/base/pattern/view-region.ts
import {
    Component,
    ContentChild,
    Input,
    TemplateRef,
    ViewContainerRef
} from '@angular/core';
import { PatternService } from './pattern.service';

@Component({
    selector: 'ViewRegion',
    template: '<ng-content></ng-content>'
})
export class ViewRegionComponent {
    @Input() name!: string;
    
    @ContentChild(TemplateRef) templateRef!: TemplateRef<any>;

    constructor(
        public container: ViewContainerRef,
        private patternService: PatternService,
    ) { }
    
    ngAfterViewInit() {
        this.patternService.render(this);
    }
}

// examples/courseman/fevuejs/src/components/common/pattern/viewregion.vue
<template>
    <div>
        <!-- Replace the placeholder with the actual content(s) provided by the patternService -->
    </div>
</template>

<script>
import PatternService from "./pattern.service";

export default {
    name: "ViewRegion",
    props: {
        name: {
            type: String,
            required: true,
        },

        patternService: {
            type: PatternService,
            required: true,
        },
    },

    mounted() {
        // Replace the placeholder with the actual content
        this.patternService.render(this);
    },
}
</script>
